//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    [Serializable]
    public class EndEffectorPoseMsg : Message
    {
        public const string k_RosMessageName = "niryo_moveit/EndEffectorPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg target;
        public double gripper_state;

        public EndEffectorPoseMsg()
        {
            this.target = new Geometry.PoseMsg();
            this.gripper_state = 0.0;
        }

        public EndEffectorPoseMsg(Geometry.PoseMsg target, double gripper_state)
        {
            this.target = target;
            this.gripper_state = gripper_state;
        }

        public static EndEffectorPoseMsg Deserialize(MessageDeserializer deserializer) => new EndEffectorPoseMsg(deserializer);

        private EndEffectorPoseMsg(MessageDeserializer deserializer)
        {
            this.target = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.gripper_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.gripper_state);
        }

        public override string ToString()
        {
            return "EndEffectorPoseMsg: " +
            "\ntarget: " + target.ToString() +
            "\ngripper_state: " + gripper_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
